/********************************************************************
* src/G__MLIB.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/G__MLIB.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__MLIB();
extern void G__cpp_setup_inheritanceG__MLIB();
extern void G__cpp_setup_typetableG__MLIB();
extern void G__cpp_setup_memvarG__MLIB();
extern void G__cpp_setup_globalG__MLIB();
extern void G__cpp_setup_memfuncG__MLIB();
extern void G__cpp_setup_funcG__MLIB();
extern void G__set_cpp_environmentG__MLIB();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TMCollection.h"
#include "TMCombinedFit.h"
#include "TMCombinedFunctor.h"
#include "TMCuts.h"
#include "TMEBin.h"
#include "TMEnergyThetaCut.h"
#include "TMFit.h"
#include "TMFitCollection.h"
#include "TMFunctor.h"
#include "TMObjectCollection.h"
#include "TMPluto.h"
#include "TMTools.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__MLIBLN_TClass;
extern G__linked_taginfo G__G__MLIBLN_TBuffer;
extern G__linked_taginfo G__G__MLIBLN_TMemberInspector;
extern G__linked_taginfo G__G__MLIBLN_TObject;
extern G__linked_taginfo G__G__MLIBLN_TNamed;
extern G__linked_taginfo G__G__MLIBLN_TString;
extern G__linked_taginfo G__G__MLIBLN_TList;
extern G__linked_taginfo G__G__MLIBLN_TF1;
extern G__linked_taginfo G__G__MLIBLN_TH1;
extern G__linked_taginfo G__G__MLIBLN_TH1D;
extern G__linked_taginfo G__G__MLIBLN_TH1F;
extern G__linked_taginfo G__G__MLIBLN_TMEBin;
extern G__linked_taginfo G__G__MLIBLN_TMCollection;
extern G__linked_taginfo G__G__MLIBLN_TH2;
extern G__linked_taginfo G__G__MLIBLN_TH2F;
extern G__linked_taginfo G__G__MLIBLN_TGraphErrors;
extern G__linked_taginfo G__G__MLIBLN_TOEnergyThetaCut;
extern G__linked_taginfo G__G__MLIBLN_TFile;
extern G__linked_taginfo G__G__MLIBLN_TOEnergyThetaData;
extern G__linked_taginfo G__G__MLIBLN_TMFitCollection;
extern G__linked_taginfo G__G__MLIBLN_TMCombinedFunctor;
extern G__linked_taginfo G__G__MLIBLN_TMCombinedFit;
extern G__linked_taginfo G__G__MLIBLN_TMEnergyThetaCut;
extern G__linked_taginfo G__G__MLIBLN_TMFunctor;
extern G__linked_taginfo G__G__MLIBLN_TMTools;
extern G__linked_taginfo G__G__MLIBLN_TMObjectCollection;
extern G__linked_taginfo G__G__MLIBLN_TMCuts;
extern G__linked_taginfo G__G__MLIBLN_TMFit;
extern G__linked_taginfo G__G__MLIBLN_TMPluto;

/* STUB derived class for protected member access */
